# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5dea30d7fa3df77d2030c50bc00c498a744702a454104acd3c6fe80c0ea29c275fe983077de73b1424e785ee8750f9ede25805e515223f15bc918ebe51e4be40

test:
  secret_key_base: 43f115745e816b1b6a6e570326da17483d9411a22f1c4bf81f1e834310dd01fc302a84f3b58c29341c1901c34e0db83e00a6dd7d25e5ba2f4bc1958c0cea5061

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
